### ISSUE TITLE
CTRL+enter to post a toot

### ISSUE THREAD

**Issue by hoodiek** [n1k0/tooty#180] opened 2017-05-23 14:56 UTC
its in the title!

**Comment by nicosomb** [comment] 2017-05-23 15:05
Hello @hoodiek ! 

Your issue is a duplicate of this one: https://github.com/n1k0/tooty/issues/60
Have a nice day.

**Closed by nicosomb** 2017-05-23 15:05 UTC

**Comment by hoodiek** [comment] 2017-05-23 15:14
thank you for point it out! sorry for duplicate
