### ISSUE TITLE
autocomplete username

### ISSUE THREAD

**Issue by DirtyF** [n1k0/tooty#96] opened 2017-04-28 14:02 UTC
As a Mastodon user following @n1k0 and @nicosomb 
When I type `@n`
Then a short list with all the people I follow beginning with `@n`(`@n1k0` and `@nicosomb`in this case) is displayed
And I can select a user to insert his username in the current toot

![image](https://cloud.githubusercontent.com/assets/103008/25532039/12a4e8ba-2c2c-11e7-8b97-4e8d65a03226.png)

**Comment by n1k0** [comment] 2017-04-28 14:03
Duplicate of #44 😇

**Closed by n1k0** 2017-04-28 14:03 UTC
