### ISSUE TITLE
Global timeline doesn't refresh

### ISSUE THREAD

**Issue by bacardi55** [n1k0/tooty#94] opened 2017-04-28 13:25 UTC
Seems that my home and notification timeline get updated as it should, but not my global timeline.

I can't speak for the local timeline, being on a private/personal instance, only my own toot are displayed there.

**Comment by vjousse** [comment] 2017-05-03 19:34
Can't reproduce this one. Can you still confirm it?

**Comment by n1k0** [comment] 2017-05-05 21:57
Can't reproduce either, closing.

**Closed by n1k0** 2017-05-05 21:57 UTC
Labels: bug
